language: perl
sudo: false
addons:
  apt:
    packages:
    - libssl-dev
perl:
  - "5.14"
  - "5.24"
branches:
  only:
    - master
install:
  - "cpanm Dist::Zilla --notest"
script:
  - "dzil authordeps --missing | cpanm --notest"
  - "dzil listdeps --missing | cpanm --notest"
  - "dzil test"
